### ISSUE TITLE
python3.vim is reported by :Startuptime but not by --startuptime

### ISSUE THREAD

**Issue by lucc** [dstein64/vim-startuptime#10]
I am using neovim on NixOS. When I execute `:Startuptime` the top of the buffer shows that python3.vim has been loaded:
```
       startup: 800.9
event                  time percent plot
packer_compiled.lua  333.30   41.62 ██████████████████████████
python3.vim          241.31   30.13 ██████████████████▉
filetype.vim          21.35    2.67 █▋
opening buffers       20.72    2.59 █▋
...
```
The details for this file are (the prefix is due to NixOS, that is just the provider file in the neovim package):
```
event: sourcing /nix/store/qyawd05zszdvcrgbvdhr2q4ay6ac4v9r-neovim-unwrapped-0.6.0/share/nvim/runtime/autoload/provider/python3.vim
start: 526.474
self: 240.351
self+sourced: 241.306
finish: 767.780
```

But I was sceptical if I use anything with python3 so I checked with `filter python scriptnames` and that returns nothing.  Here is also a [startup.log](https://github.com/dstein64/vim-startuptime/files/7776704/startup.log) generated with `nvim --startuptime startup.log +q` for reference. It does not contain the string `python` anywhere.

Why does `:StartupTime` show this python3.vim file but `--startuptime` and `:scriptnames` don't?

**Comment by dstein64** [comment]
Hi @lucc, in the `startup.log` file you uploaded, the last line is for a sourcing event. It's possible that Neovim has exited prior to finishing all its usual startup events. Can you try again without adding `+q` to the command you ran? This will require that you quit manually. The last event in `startup.log` should be `--- NVIM STARTED ---`.

`vim-staruptime` includes [logic](https://github.com/dstein64/vim-startuptime/blob/1174d5a7f5b2992ffce1624f171d807d393c2373/autoload/startuptime.vim#L240-L268) intended to avoid dropping startup events.

**Comment by lucc** [comment]
Here is the new file: 
[startup.log](https://github.com/dstein64/vim-startuptime/files/7777608/startup.log). It still does not contain any reference to any python.vim file.

**Comment by lucc** [comment]
My nvim config is here: https://github.com/lucc/vim-config 

But it uses quite some plugins and external dependencies. If you want I can try to create a minimal example during the next days.

**Comment by dstein64** [comment]
I think the `python3.vim` file is loaded as a result of loading [nvim-yarp](https://github.com/roxma/nvim-yarp), which depends on Python 3, in [lsp.lua](https://github.com/lucc/vim-config/blob/8356b07874ec5fe72a12c366b839f89261a1de50/lua/plugins/lsp.lua#L157).

I don't know why `python3.vim` would be run when calling `:StartupTime`, but not when using `--startuptime` directly, since `vim-startuptime` obtains timing data by using `--startuptime`. Perhaps it relates to the [lazy loading](https://github.com/roxma/nvim-yarp/blob/b710bf4daccb603a423754794fb446e5fbb59576/README.md?plain=1#L36) used by `nvim-yarp`.

**Comment by dstein64** [comment]
I see that you have [commented out code](https://github.com/lucc/vim-config/blob/8356b07874ec5fe72a12c366b839f89261a1de50/lua/options.lua#L187) that sets `g:python3_host_prog`.

Does `g:python3_host_prog` get set as part of some global configuration script (e.g., `/etc/xdg/nvim/sysinit.vim`)? If so, that could explain why the Python 3 provider script does not run when you use `--startuptime`. However, that wouldn't explain the difference between using `--startuptime` and `:StartupTime`, since `:StartupTime` would presumably use that configuration as well.

If setting `g:python3_host_prog` is resulting in no Python 3 provider script running when using `--startuptime`, are you using `g:startuptime_exe_args` or any environmental settings that could alter the setting of `g:python3_host_prog` by time `:StartupTime` runs? For example, if you're using a `-u` argument with `g:startuptime_exe_args`, that might prevent the loading of global configuration scripts (for Vim, when `-u` is used, "all the other initializations are skipped").

**Comment by dstein64** [comment]
I see that there is Nix [logic](https://github.com/NixOS/nixpkgs/blob/bd7587ea9340139e7fb4c86346854dd4db5cd298/pkgs/applications/editors/neovim/wrapper.nix#L63) for wrapping Neovim for Python 3 support.

Perhaps when you run Neovim, `g:python3_host_prog` (or some other way of specifying a Python path) has already been configured by the wrapper.

Then `:StartupTime` uses the unwrapped binary (`exepath(v:progpath)`), where `g:python3_host_prog` is not already set, resulting in the Python 3 provider script running.

If this is the case, a workaround could be to set `g:startuptime_exe_path` to the path of the wrapped Neovim launcher prior to calling `:StartupTime`.

**Comment by lucc** [comment]
I tried setting `g:startuptime_exe_path` and that solves the issue. Thanks for your help!
