### ISSUE TITLE
doesn't work in vim, works fine in neovim?

### ISSUE THREAD

**Issue by jgb** [dstein64/vim-startuptime#11]
Hello,

this plugin worked for me previously, but now it doesn't anymore (latest git version).
In neovim it works fine, however in vim / gvim I just end up with this in a vsplit:

```
# vim-startuptime
Running: [100%]
```

Any ideas what might be wrong?
I'm on vim/gvim 8.2.3995 on debian testing/unstable.

Greetings,

jgb

**Comment by dstein64** [comment]
Thanks for reporting this @jgb!

I recently ported some functions to `vim9script`, which I think is causing the problem you've encountered.

I've updated the code in de7bc43350ea3ea25fddfe43a00224f7f850efa0 to check for a necessary Vim patch in order to use the `vim9script` functions.

I'll close this ticket. Please re-open and/or let me know if the update doesn't address the problem for you.
