### ISSUE TITLE
[Feature Request] Show average total time

### ISSUE THREAD

**Issue by wbthomason** [dstein64/vim-startuptime#4]
While it's great to see the percent breakdown of each event, it would also be useful to display the (average, for multiple tries) total startup time at the top of the `startuptime` buffer.

**Comment by dstein64** [comment]
The functionality you've requested is available.

`:StartupTime` takes an optional argument, `--tries`, for specifying how many runs to conduct. The results are averaged.

E.g.,
```
:StartupTime --tries 20
```

Additionally, pressing `<space>` with the cursor on the header row will show additional information, including the total time (an averaged total if `--tries` was used).

**Possibly Relevant Additional Information**

The numbers reported by the `vim-startuptime` plugin are obtained by calling Vim with the `--startuptime` option, which reports both `self` times and `self+sourced` times. As far as I can tell, based on the information in `:help profd` (assuming the info applies generally to timings reported by `--startuptime`), the `self` times exclude time spent performing various actions (e.g., sourcing other files), whereas the `self+sourced` times include these various other actions.

The `vim-startuptime` plugin uses the `self+sourced` times by default (e.g., for individual times, total times, and percent calculations). The optional `--no-self` option can be specified so that only `self` timings are reported and used for calculations.

**Comment by wbthomason** [comment]
Ah, I did not realize that using `<space>` on the header line would show the total time. That's the part I was missing. Thanks!
