### ISSUE TITLE
Feature: Add a config option to display total in StartupTime report

### ISSUE THREAD

**Issue by reportaman** [dstein64/vim-startuptime#6]
I tend to look more for total time, and as of now I it is show in the message area at the bottom of the screen instead of being shown with the report. It would be nice to have a configuration option to show the sum on top row before any other time, something like this:

```
event                  time percent plot
------                ----- ------- ----
total                250.00  100.00 
.vimrc                41.55   21.01 ██████████████████████████
```

**Comment by dstein64** [comment]
Thanks for your feature request @reportaman!

The total time for starting up is now reported at the top of the output.

Because events can overlap (i.e., when `--no-sourcing` is not used) and not all startup time is captured by events, the sum of values in the `time` column won't necessarily equal the reported startup time. Additionally, the sum of percentages won't necessarily sum to 100%, as they're now calculated using the total startup time in the denominator (as opposed to using the sum of the time column).

<img width="1280" alt="startuptime_annotated" src="https://user-images.githubusercontent.com/541289/126927010-82d13a2e-1be9-48b6-ada9-a2ba162bf470.png">

**Comment by reportaman** [comment]
@dstein64 Thanks for the update & explanation!
